config/routes.rb
Rails.application.routes.draw do
  get "/movies", to: "movies#index", as: "movies"
  post "/movies", to: "movies#create"
  get "/movies/new", to: "movies#new", as: "new_movie"
  get "/movies/:id", to: "movies#show", as: "movie"
  put "/movies/:id", to: "movies#update"
  get "/movies/:id/edit", to: "movies#edit", as: "edit_movie" 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    def index
    end

    def create
        #puts params 
        if session[:movies] == nil 
            session[:movies] = []
        end 
        session[:movies].push(params[:movie])
        redirect_to movie_path(session[:movies].length)
    end

    def new
    end

    def show
        # exmaple of what's going in code below: session[:movies] = ["Avengers", "the dark knight"]
        @movie = session[:movies][params[:id].to_i - 1]
    end

    def edit
        @movie = session[:movies][params[:id].to_i - 1]
    end

    def update
        session[:movies][params[:id].to_i - 1] = params[:movie]
        redirect_to movie_path(params[:id].to_i)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FormsHtmlRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/edit.html.erb
<h1>Edit movie</h1>

<%# every form can make a post request  %>
<form action="<%= movie_path(params[:id])%>" method="POST">
    <input type="hidden" name="_method" value="put">
    <label>Title</label>
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
    <input type="text" name="movie[title]" value="<%= @movie["title"]%>">
    <br><br>
    <label>Rating<label>
    <input type="number" name="movie[rating]" min="1" max="10" value="<%= @movie["rating"]%>">
    <br><br>
    <input type="submit" value="Update movie">
</form>

app/views/movies/index.html.erb
<h1>List movies</h1>

app/views/movies/new.html.erb
<h1>New movie</h1>
<%# every form can make a post request  %>
<form action="<%= movies_path%>" method="POST">
    <label>Title</label>
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
    <input type="text" name="movie[title]">
    <br><br>
    <label>Rating<label>
    <input type="number" name="movie[rating]" min="1" max="10">
    <br><br>
    <input type="submit" value="Create movie">
</form>

app/views/movies/show.html.erb
<h1>Show movie</h1>

<h2>Title: <%=@movie["title"]%></h2>
<p>Rating: <%= @movie["rating"]%> </p>
<%=link_to "back", :back %>
<%=link_to "edit", edit_movie_path(params[:id]) %>